### PR TITLE
add text for adoption of .njk extension

### PR DESCRIPTION
**Pull request by dkebler**
with this small edit it was easier to just start over with your latest commit with multiple edits. of templating.md.  Also made all textual lowercase nunjucks to Nunjucks

### CODE REVIEW

**Comment by carljm** [comment]
Thanks!

**Comment by ArmorDarks** [comment]
Great, though, we always used just `*.nj` for years...

Maybe now would be appropriate time to overlook https://github.com/mozilla/nunjucks/issues/475?

**Comment by carljm** [comment]
Nothing wrong with continuing to use `.nj` if you prefer it, but I think it's useful to have a documented preference. No matter what we picked, it wouldn't match what someone out there has been using...

I still don't like #475 -- I think the recommended extension should remain a matter only for the documentation and the community, not something that has an actual effect on the behavior. Even if it were configurable, I still don't see the benefit -- it makes your includes etc correspond less clearly to the actual template files, why is that a good thing?

**Comment by ArmorDarks** [comment]
> Nothing wrong with continuing to use .nj if you prefer it, but I think it's useful to have a documented preference. No matter what we picked, it wouldn't match what someone out there has been using...

Sure. Just wonder, why was chosen `.njk`? I didn't find any discussion about it. Did I miss something? Just curios.

Anyways, it definitely not that important, but just my two cents. It seems strange to have ending `k`. It's like to have `.jst` for JavaScript just because it ends with `t`.

> I still don't like #475 -- I think the recommended extension should remain a matter only for the documentation and the community, not something that has an actual effect on the behavior. Even if it were configurable, I still don't see the benefit -- it makes your includes etc correspond less clearly to the actual template files, why is that a good thing?

I've replied here https://github.com/mozilla/nunjucks/issues/475#issuecomment-215259279 to avoid off-topic.

**Comment by carljm** [comment]
It was discussed briefly on the Google group mailing list. I said I didn't care between `nj` and `njk`, and would leave it up to whoever submitted a PR to paint the bikeshed. I have a slight preference toward `nj` myself, but I don't really care.

**Pull request merged**
