### PR TITLE
Adds switch tag, as featured in Craft CMS and Liquid. Addresses #967.

### LINKED ISSUE #967: Feature request: Add switch statement
Hello,

It would be great if there was a `{% switch %}` statement in nunjucks

Something like the following:

```
{% switch someVar %}
  {% case 'value1' %}
   ...
  {% case 'value2' %}
   ...
  {% case 'value3' %}
   ...
  {% default %}
   ...
{% endswitch %}
```

I'm relatively new to nunjucks so i'm not sure of the complexities involved in adding something like this.  I saw this: https://mozilla.github.io/nunjucks/api.html#custom-tags, but it's a little bit beyond me! 

Cheers

### PR DESCRIPTION
**Pull request by noahlange**
## Summary

Proposed change:

Adds a switch tag, as featured in [Liquid](http://shopify.github.io/liquid/tags/control-flow/#casewhen) and [Craft CMS](https://craftcms.com/docs/templating/switch), and as requested in [#967](https://github.com/mozilla/nunjucks/issues/967).

It works about how you'd expect. Switch on a variable, provide cases with potential values, and then an optional default case.

Still need to write docs + changelog entries.

**CAVEAT:** Unlike in JS, cases break automatically. There's no explicit break.
**CAVEAT**: Unlike in Liquid, switch tags use JS nomenclature (instead of Ruby's `case`/`when`/`else` ). It's much closer to Craft's implementation in that regard. If this is an issue, the code is written so that tag names can be easily swapped out.

```django
{% switch foo %}
  {% case 'bar' %}
    BAR
  {% case 'baz' %}
    BAZ
  {% default %}
    NEITHER BAR NOR BAZ
{% endswitch %}
```

The compiled code is fairly straightforward.

```js
function root(env, context, frame, runtime, cb) {
  var lineno = null;
  var colno = null;
  var output = '';
  try {
    var parentTemplate = null;
    switch (runtime.contextOrFrameLookup(context, frame, 'foo')) {
      case 'bar':
        output += 'BAR';
        break;
      case 'baz':
        output += 'BAZ';
        break;
      default:
        output += 'NEITHER FOO NOR BAR';
    }
    if (parentTemplate) {
      parentTemplate.rootRenderFunc(env, context, frame, runtime, cb);
    } else {
      cb(null, output);
    }
  } catch (e) {
    cb(runtime.handleError(e, lineno, colno));
  }
}

return {
  root: root
};
```
Closes #967 .

## Checklist

I've completed the checklist below to ensure I didn't forget anything. This makes reviewing this PR as easy as possible for the maintainers. And it gets this change released as soon as possible.

* [X] Proposed change helps towards [*purpose of this project*](https://github.com/mozilla/nunjucks/blob/master/CONTRIBUTING.md#purpose).
* [ ] [*Documentation*](https://github.com/mozilla/nunjucks/tree/master/docs/) is added / updated to describe proposed change.
* [X] [*Tests*](https://github.com/mozilla/nunjucks/tree/master/tests) are added / updated to cover proposed change.
* [ ] [*Changelog*](https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md) has an entry for proposed change (if user-facing fix or feature).

### CODE REVIEW

**Comment by ArmorDarks** [comment]
I'm somehow against going beyond what Jinja2 offers. Such kind of functionality should go through Jinja2 Github issues at first, where we can receive better community feedback, and only in case of approval implement it here.

Also, ignoring Jinja2 will take Nunjucks even further from original idea of compatible templating language. It would be understandable if Jinja2 is dead and does not evolve, thus holding Nunjucks back from further evolution. But it isn't dead.

Well, that's just imho.

**Comment by noahlange** [comment]
Hmm. If it weren't a requested feature and implemented in two members of the Jinja family, I  wouldn't have bothered - I could probably rewrite it as a custom tag plugin.

**Comment by fdintino** [comment]
I'm going to merge this as-is, with an eye towards making non-standard jinja tags into some sort of contrib module (either part of this repo, or as a separately installed repo).

**Comment by revolter** [comment]
When will this be [documented](https://mozilla.github.io/nunjucks/templating.html)?

**Pull request merged**
