### PR TITLE
Add getGlobal() function

### PR DESCRIPTION
**Pull request by atorkhov**

### CODE REVIEW

**Comment by garygreen** [comment]
Do you have a use case for this?

**Comment by atorkhov** [comment]
Yes, I'm doing unit tests and checking custom filters and global functions behaviour. To get filters I can use getFilter(), but for globals I need to expose them in my application somehow.

**Comment by garygreen** [comment]
Ok cool, would you mind adding some tests in `tests/global.js` for this?

**Comment by atorkhov** [comment]
Updated pull request with test and docs.
One question through - are globals really supposed to be same across all enviroments?

**Comment by devoidfury** [comment]
In a node environment, you can get access to the globals with `var nunjucks_globals = require('nunjucks/src/globals.js');`

**Comment by atorkhov** [comment]
I'm using it in browser environment.

**Comment by atorkhov** [comment]
Thanks. Any comment on are globals really supposed to be same across all environments or not?

**Comment by garygreen** [comment]
At the moment globals are the same across all environments.

**Pull request merged**
