### PR TITLE
Update `default` filter

### PR DESCRIPTION
**Pull request by cahnory**
Add the `boolean` argument documented in http://jinja.pocoo.org/docs/dev/templates/#default.

I wonder if `null` should be treated as undefined. (see https://github.com/mitsuhiko/jinja2/blob/master/jinja2/filters.py#L267)

### CODE REVIEW

**Comment by jlongster** [comment]
I think it's worth looking at this as a small backward incompatible change for 2.0. We could make `default` be strict and add another filter that does the same loose checking that it does now.

**Comment by carljm** [comment]
I'm not sure that "another filter that does the same loose checking" is really worth it, given that `or` works equally well for that purpose and is actually less verbose.

**Comment by jlongster** [comment]
That's true. If `or` is equivalent, we don't really need it.

**Comment by jlongster** [comment]
@carljm thinking about this more, I'm really uncomfortable changing the current default filter. That's just one of those changes that might make it really hard to upgrade for some codebases (or worse, introduce subtle bugs).

I'm considering just introducing a new filter that is strict by default and just deprecating `default`, eventually we can remove it and tell people to use `or`.

**Comment by carljm** [comment]
I don't think the upgrade would be that difficult (if you want the same semantics, just switch to `or` - it's doable with a regex search-and-replace). But it certainly could result in subtle bugs if people don't read the release notes and make the change.

From my perspective (where Jinja compatibility matters), adding a new filter under a different name with the Jinja behavior doesn't help at all. But if you want to do it, doesn't matter to me.

**Comment by jlongster** [comment]
I've moved this over to https://github.com/mozilla/nunjucks/pull/428 where I am implementing the change in a safe way. People can use `a or b` to get the previous semantics, or pass true like `a | default(b, true)`

**Pull request closed without merging**
