### PR TITLE
Nunjucks : Replaced PhantomJS with ChromeHeadless

### PR DESCRIPTION
**Pull request by ossdev07**
## Summary

Proposed change: 

Phantomjs is an unmaintained project.So removed phantomjs dependency from package.json and runtests.js. Added support for chrome headless to run the test suite.

Closes https://github.com/mozilla/nunjucks/issues/1236

## Checklist

I've completed the checklist below to ensure I didn't forget anything. This makes reviewing this PR as easy as possible for the maintainers. And it gets this change released as soon as possible.

* [X] Proposed change helps towards [*purpose of this project*](https://github.com/mozilla/nunjucks/blob/master/CONTRIBUTING.md#purpose).
* [X] [*Documentation*](https://github.com/mozilla/nunjucks/tree/master/docs/) is added / updated to describe proposed change.
* [X] [*Tests*](https://github.com/mozilla/nunjucks/tree/master/tests) are added / updated to cover proposed change.
* [ ] [*Changelog*](https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md) has an entry for proposed change (if user-facing fix or feature).

### CODE REVIEW

**Comment by ossdev07** [comment]
Please can someone have a look at this PR.

**Comment by ossdev07** [comment]
Please can someone have a look at this PR.

**Comment by ossdev07** [comment]
Please can someone have a look at this PR.

**Comment by fdintino** [comment]
Please stop posting the same comment repeatedly.

As I had noted in #1236, there is utility in continuing to use phantomjs (in _addition_ to chrome headless) precisely _because_ it's unmaintained and doesn't have any ES6 features. It ensures that the package is properly transpiled and has the necessary polyfills. In that way it's a useful stand-in for IE 9, old Androids, etc.

I'm going to be going in a direction that uses both. I have [a draft of that](https://github.com/mozilla/nunjucks/blob/53c9a63591ae4fd3c4614bd44ce1547646727380/scripts/runtests.js) on the [develop](https://github.com/mozilla/nunjucks/compare/develop) branch, which will eventually become nunjucks v4

**Comment by ossdev07** [comment]
Thank you for the reply.
Phantomjs is unmaintained and it does not support many architectures like ARM64, so if we will keep phantom this will not run on those architectures.
Please suggest.

**Pull request closed without merging**
