### PR TITLE
change the output library target to commonjs2.

### PR DESCRIPTION
**Pull request by mohannadsh**
In the current version, when I use the nunjucks in the browser using nunjucks = require('nunjucks');, I recieve an empty object, and I cannot use nunjucks to render templates.

The suggested solution is to change the target to commonjs2, so that the nunjucks methods are exported to the module.

### CODE REVIEW

**Comment by carljm** [comment]
See discussion on #507.

**Comment by mohannadsh** [comment]
I saw the discussion, I tried the exports-loader and it didn't export the whole nonjucks object, I think that this is a simpler fix, What do you think, do you see any issue with it?

**Comment by ingro** [comment]
@mohannadsh I solved with exports-loader by doing this:
```
{
    test: /nunjucks\.js/,
    loader: 'exports?nunjucks'
}
```

Didn't work with `test: /nunjucks\/browser\/nunjucks\.js$/,`

**Comment by Rowno** [comment]
FYI, exports-loader doesn't help Browserify users.

**Comment by mohannadsh** [comment]
@Rowno 
You're right, exports loader didn't work with me.

**Comment by mohannadsh** [comment]
@carljm 
Are you going to push this change?

**Comment by carljm** [comment]
@mohannadsh I'm not sure. I'm not an expert on JS modules stuff; I'm hoping @jgerigmeyer or another contributor will weigh in on this and #507 and make a decision on where to go with it.

**Comment by carljm** [comment]
(BTW this needs rebasing and a conflict resolved before it can be merged, but you may not want to bother with that until we make a decision about how to handle nunjucks packaging going forward.)

**Comment by jgerigmeyer** [comment]
I'd prefer a UMD wrapper so that it still works natively in the browser. See https://github.com/mozilla/nunjucks/pull/606.

**Comment by carljm** [comment]
@mohannadsh Does that resolution work for you?

**Pull request closed without merging**
