### PR TITLE
Support objects created with Object.create(null)

### LINKED ISSUE #468: obj.hasOwnProperty undefined is not a function nodejs
Hello,

I was noticing some discrepancies in some of the rendering of the nunjuck templates. After enough digging around I boiled it down to different nodejs versions between development and production. However the production machine has a more resent version of nodejs.

```
~ > node --version
v0.12.2
```

With version v0.12.x of node, this line

https://github.com/mozilla/nunjucks/blob/master/src/lib.js#L271

fails with **TypeError: undefined is not a function.**

Has anyone encountered this, is there any know workaround?

### PR DESCRIPTION
**Pull request by asprouse**
## Summary

Proposed change:

Support objects created with Object.create(null) by following the [no-prototype-builtins](http://eslint.org/docs/rules/no-prototype-builtins). This fix is important because it makes nunjucks compatible with this widely used ES5 feature (Object.create).

Closes #468

## Checklist

I've completed the checklist below to ensure I didn't forget anything. This makes reviewing this PR as easy as possible for the maintainers. And it gets this change released as soon as possible.

* [x] Proposed change helps towards [*purpose of this project*](https://github.com/mozilla/nunjucks/blob/master/CONTRIBUTING.md#purpose).
* [x] [*Documentation*](https://github.com/mozilla/nunjucks/tree/master/docs/) is added / updated to describe proposed change.
* [x] [*Tests*](https://github.com/mozilla/nunjucks/tree/master/tests) are added / updated to cover proposed change.
* [x] [*Changelog*](https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md) has an entry for proposed change (if user-facing fix or feature).

Note no documentation update was necessary.

### CODE REVIEW

**Comment by ArmorDarks** [comment]
This isn't related to PR directly, but I still can't get why would someone create object from `null`?

**Comment by ArmorDarks** [comment]
Also, here https://github.com/mozilla/nunjucks/issues/468#issuecomment-115026511 said that this method doesn't work that well in older browsers.

**Comment by asprouse** [comment]
@ArmorDarks creating an object using `Object.create(null)` creates an object without a prototype which is suitable for using as a map. Instead of calling `obj.hasOwnProperty(x)` to check membership one can simply `obj[x]`. It seems that this is a technique used is several popular libraries (express and graphql off the top of my head).

As far as compatibility goes this PR only changes how hasOwnProperty is called `obj.hasOwnProperty(x)` -> `Object.prototype.hasOwnProperty.call(obj, x)`. Both [hasOwnProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty) and [call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call) predate ES5 (ES3 and ES1 according to MDN) so even IE8 support shouldn't be a problem.

**Comment by fdintino** [comment]
Thanks for the PR! I agree that `Object.prototype.hasOwnProperty.call(obj)` is preferable to `obj.hasOwnProperty()`.

**Pull request merged**
