### PR TITLE
Make each nunjucks environment have its own globals property

### PR DESCRIPTION
**Pull request by thepechinator**
This is for the shared globals between environments issue mentioned in https://github.com/mozilla/nunjucks/issues/573. Let me know if you'd like me to revise anything.

Here's what's included:
- Added a test case.
- Updated test/util.js's equal method to take in an optional env parameter, since globals aren't shared between environments anymore.
- Updated Context in src/environment.js to take in an optional env parameter, for same reason.

Thanks!

### CODE REVIEW

**Comment by carljm** [comment]
Looks great! Can you also add a note to the CHANGELOG file? Thanks!

**Comment by thepechinator** [comment]
Done. Thanks for the quick review.

**Comment by thepechinator** [comment]
Had to fix conflicts with PR #575, which was merged into master. carljm, is there anything else I need to do before this can be merged into master?

**Comment by carljm** [comment]
Nope, looks good, merging! Sorry, must have missed the email notification on your update.

**Pull request merged**
