### PR TITLE
add missing quote

### PR DESCRIPTION
**Pull request by pd4d10**
## Summary

Proposed change:

Add missing quote in Chinese documentation.

## Checklist

I've completed the checklist below to ensure I didn't forget anything. This makes reviewing this PR as easy as possible for the maintainers. And it gets this change released as soon as possible.

* [x] Proposed change helps towards [*purpose of this project*](https://github.com/mozilla/nunjucks/blob/master/CONTRIBUTING.md#purpose).
* [x] [*Documentation*](https://github.com/mozilla/nunjucks/tree/master/docs/) is added / updated to describe proposed change.
* [x] [*Tests*](https://github.com/mozilla/nunjucks/tree/master/tests) are added / updated to cover proposed change.
* [x] [*Changelog*](https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md) has an entry for proposed change (if user-facing fix or feature).

### CODE REVIEW

**Comment by vecmezoni** [comment]
Thanks!

**Comment by vecmezoni** [comment]
Pooh! @pd4d10, could you please provide pull request for master branch? You'd fixed this in `gh-pages` branch that is being just generated from `master`.

**Comment by pd4d10** [comment]
It seems that `redcarpet with_toc_data` couldn't correctly handle non-ASCII character, https://github.com/vmg/redcarpet/issues/538

This is a temporary solution to make this doc display correctly.

**Comment by vecmezoni** [comment]
That's sad. Your fix will break with next release 😿

**Pull request merged**
