### PR TITLE
Add nonbreaking space to whitespace chars list

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR fixes the issue #351.

### CODE REVIEW

**Comment by SamyPesse** [comment]
jinja2 treats the non-breaking space as valid whitespace. https://github.com/mitsuhiko/jinja2/blob/c97fa109d38b5367ce3efffb6e435d007dc55920/docs/api.rst#L85

**Comment by jlongster** [comment]
Sounds great. Can we get a test in tests/lexer.js for this? I can do it if you want me to.

**Comment by SamyPesse** [comment]
Done :beers: https://github.com/mozilla/nunjucks/commit/8b81acbc67594c59a2200ee289df37b8e5c322bf

**Comment by jlongster** [comment]
Thanks! Will cut a minor release soon

**Comment by SamyPesse** [comment]
Ok thanks :+1: :beers: what about relative includes ? do you want to merge it and release it or it needs more work ?

**Comment by jlongster** [comment]
I was going to look at that this morning but I got busy with work. I'd like to give it a more thorough review, and I should be able to get to it tomorrow.

**Pull request merged**
