### PR TITLE
fixes issue #709: filters inside import tags

### PR DESCRIPTION
**Pull request by legutierr**
Fix for #709.

### CODE REVIEW

**Comment by legutierr** [comment]
Hi @carljm , any thoughts on this pull request?

**Comment by carljm** [comment]
Not yet, still digging out from vacation backlog :-) Nunjucks catch-up is on the todo list.

**Comment by carljm** [comment]
LGTM! Would you mind adding a changelog entry, per the existing style? Once that's done I'll merge. Thanks!

**Comment by legutierr** [comment]
Hi @carljm , I think this is ready to go :)

**Comment by carljm** [comment]
Thanks, merged!

**Comment by legutierr** [comment]
Thank you, @carljm !

**Pull request merged**
