### PR TITLE
Remove ancient Node.js compatibility workaround

### PR DESCRIPTION
**Pull request by shvaikalesh**

### CODE REVIEW

**Comment by vecmezoni** [comment]
Could you please supply a note to the changelog?

**Comment by shvaikalesh** [comment]
@vecmezoni I would gladly do that, but is necessary since `precompile` already uses `fs.existsSync` wo fallback: https://github.com/mozilla/nunjucks/blob/master/src/precompile.js#L42?

**Comment by vecmezoni** [comment]
Ok, but i don't see any reason not to add a line to a changelog.

**Comment by vecmezoni** [comment]
👍

**Pull request merged**
