### PR TITLE
Add tests and workaround for #189

### PR DESCRIPTION
**Pull request by metasansana**

### CODE REVIEW

**Comment by garygreen** [comment]
Thanks for this, there's a few issues though e.g. if you pass through a non-string, like a number, it should still handle it.

I have an idea for a more generic implementation which I will try and get around to later

**Comment by shainab** [comment]
@garygreen  Ok, Let me know if you want me to modify this instead then.

**Comment by metasansana** [comment]
@garygreen Ok, Let me know if you want me to modify this instead then.

**Comment by jlongster** [comment]
Yeah. This is basically silently failing if the value isn't a string. I suspect most of the time the value *should* be a string, and I personally like being a little more strict about that. The behavior right now errors, basically telling the user that they did something wrong. However, I'm fine if we go the other way with some of these builtin filters and coerce the value to a string instead.

We definitely don't want to show nothing if it's not a string. That seems ripe for confusion. ("why isn't this showing up??" and then they have to spend time figuring out they accidentally passed an integer)

We could follow the same rules as we do when outputting a value: only show nothing for `null` & `undefined` (and `false`? I can't remember). Otherwise, we just call `toString()` on it.

**Comment by garygreen** [comment]
Well I was thinking about a basic map of 'default values' if your passing a value that is either `null` or `undefined` to a filter. Could even make it an option like `strict_filters` or something. Was thinking of something along the lines of the below, where it would check the emptyDefaults mapping before passing the value onto the filter if it's null or undefined:

```javascript
var emptyDefaults = {
	abs: 0,
	center: '',
	first: [],
	join: []
};
```

**Comment by jlongster** [comment]
That's a good point; each filter wants to default to something different. I think it might be more appropriate as a utility function though, which each filter calls with the value (like `normalize(val, [])`) and gives it a default.

**Comment by garygreen** [comment]
Sounds good

**Comment by metasansana** [comment]
There is a `default` filter. Should I call that then pass it to `string`? Or maybe add `normalize` and a `stringify` method to `lib`?

**Comment by jlongster** [comment]
I would say do the following:

1. Create just a simple top-level function in `filters.js` that looks like this:

```js
function value(v, default) {
  if(v === null || v === undefined || v === false) {
    return default;
  }
  return v;
}
```

2. Use this at the top of the filters that should support falsy values. So at the top of  `center`, for example, it would be `str = value(str, '')`.

That way there's just one place where we specify the rules of how to treat values.

**Comment by garygreen** [comment]
I would not do the `v === false` check as that assumes too much, this is more to do with nullable/undefined values.

**Comment by jlongster** [comment]
I'm down with that.

**Comment by jlongster** [comment]
This was fixed in #403, we basically did the same thing we talked about here for normalizing the inputs.

**Comment by metasansana** [comment]
I fell into a black hole with some client work, sorry. :(  Thank you all for addressing this though.

**Pull request closed without merging**
