### PR TITLE
emit update when the template is changed the first time when the event =...

### PR DESCRIPTION
**Pull request by MaxKramnik**
...= "add". The template would not update when it is modified first time. The watcher listens only to the "change" event. The first event is actually "add".

### CODE REVIEW

**Comment by jlongster** [comment]
Isn't `add` when a new file is created? Are you saying that when you first fire up the app, load a page, and change an existing template the updates don't show up the first time? I can't reproduce that.

**Comment by MaxKramnik** [comment]
James,

Yeah, load the page, then make a template file change, refresh the page, the change is not there. If you make another change, save, refresh the page, both changes show up.

Thanks,

Max

**Comment by jlongster** [comment]
I think we can take the `ignoreInitial` option off actually. Without it the `add` event is emitted immediately, and we will just ignore it. The first save should then be a `change` event. I can't remember why we added that option. Chokidar may have changed behavior in a recent version.

Can you update your PR to remove that option?

**Comment by MaxKramnik** [comment]
Removing ignoreInitial worked, thanks!

**Pull request merged**
