### PR TITLE
Added option to customize the wrapper for precompiled templates

### PR DESCRIPTION
**Pull request by rhengles**
Users can use this options to store templates in modules, for example.

### CODE REVIEW

**Comment by rhengles** [comment]
Can you give me an idea of what you're considering refactor here? Can this be considered for 2.0 (#347)?

**Comment by jlongster** [comment]
@rhengles I'm taking a look at this again, and I think we could do this with a minor bump (1.2 -> 1.3). I'd like to review this a little more before accepting it though.

**Comment by jlongster** [comment]
Ok I'm definitely looking at this again. If we break the precompile API it may be reason enough for 2.0. No need to worry about bumping the major version.

**Comment by jlongster** [comment]
You've convinced me, I'll merge this in and play with it locally to make sure everything works.

**Comment by jlongster** [comment]
Actually, it looks like this is backwards-compatible. I thought you replaced the `asFunction` option but it's still there. this should be fine.

**Comment by rhengles** [comment]
:+1: :100: Thanks man!

**Pull request merged**
